### ISSUE TITLE
Fix for Windows

### ISSUE THREAD

**Issue by necrogami** [asticode/go-astisplash#1]
Windows 10
go version go1.9.2 windows/amd64

Downloaded the code and ran go run example\main.go -v

It loads a frame but never loads the splash.
I even hard coded the splash path and it still didn't work.

```C:\Users\Anton\go\src\github.com\asticode\go-astisplash\example>go run main.go -v
DEBU[0000] Building splasher...
DEBU[0000] Disembedding to C:\Users\Anton\AppData\Local\Temp\go-build033270906\command-line-arguments\_obj\exe
DEBU[0000] Disembedded to C:\Users\Anton\AppData\Local\Temp\go-build033270906\command-line-arguments\_obj\exe\astisplash.exe
DEBU[0000] Splashing...
DEBU[0000] Executing C:\Users\Anton\AppData\Local\Temp\go-build033270906\command-line-arguments\_obj\exe\astisplash.exe -bC:/Users/Anton/go/src/github.com/asticode/go-astisplash/example/splash.png -w484 -h316
DEBU[0000] Sleeping...
DEBU[0005] Removing C:\Users\Anton\AppData\Local\Temp\go-build033270906\command-line-arguments\_obj\exe\astisplash.exe```

**Comment by asticode** [comment]
@necrogami sorry for that, but this project still has problems on Windows. I've updated the README accordingly.

Nervertheless, if you feel like making a PR to fix it on Windows, I'd be happy to review your PR :)

**Comment by xDuck** [comment]
Are there any plans to resolve this? Or alternative libraries?

**Comment by asticode** [comment]
> Are there any plans to resolve this?

No but I had started the [job](https://github.com/asticode/go-astisplash/blob/master/splashmake/windows.c) just didn't have the time to finish it. Feel free to submit a PR

> Or alternative libraries?

Not that I know of.
